name: End-to-end tests
on:
  pull_request_review:
    types: [submitted]
    branches: ['master']
    paths: [' **path/**']
  workflow_dispatch: ~
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - id: 'reviews'
        uses: 'jrylan/github-action-reviews-counter@main'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Checkout
        uses: actions/checkout@v2
        if: 'steps.reviews.outputs.approved >= 1'
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
        if: 'steps.reviews.outputs.approved >= 1'
      - run: yarn install
        if: 'steps.reviews.outputs.approved >= 1'
      - run: yarn test:e2e:ci
        if: 'steps.reviews.outputs.approved >= 1'
