name: End-to-end tests
on:
  pull_request_review:
    types: [submitted]
    branches: ['master']
    paths: [' **path/**']
  workflow_dispatch: ~
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echo ${{ toJson(github.event.pull_request) }}
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn test:e2e:ci
